### ISSUE TITLE
Cycle dependency

### ISSUE THREAD

**Issue by jvaclavik** [markerikson/rsk-github-issues-example#14]
There is a cycle dependency in the repository:

```
src/features/issuesList/issuesSlice.ts
src/app/store.ts
src/app/rootReducer.ts
src/features/issuesList/issuesSlice.ts
```

**Comment by markerikson** [comment]
Type-only cycles are fine - the TS compiler can handle those okay.  Thus, we can import a slice reducer into `rootReducer`, import `RootState` into `Store`, and import both `RootState` and `AppThunk` back into a slice.
