### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by Jet12138** [markerikson/rsk-github-issues-example#20]
rtk-github-issues-example/node_modules/jest-diff/build/index.d.ts
TypeScript error in E:/myself/rtk-github-issues-example/node_modules/jest-diff/build/index.d.ts(10,13):
'=' expected.  TS1005

     8 | import { diffLinesRaw, diffLinesUnified, diffLinesUnified2 } from './diffLines';
     9 | import { diffStringsRaw, diffStringsUnified } from './printDiffs';
  > 10 | import type { DiffOptions } from './types';

**Comment by markerikson** [comment]
That looks like an issue with a Jest-related dependency, not anything to do with the app code. Nothing we can do about that.
